export const FETCHING_COIN_DATA = 'FETCHING_COIN_DATA';
export const FETCHING_COIN_DATA_SUCCESS = 'FETCHING_COIN_DATA_SUCCESS';
export const FETCHING_COIN_DATA_FAIL = 'FETCHING_COIN_DATA_FAIL';
export const FETCHING_ETH_PRICE_DATA = 'FETCHING_ETH_PRICE_DATA';
export const FETCHING_ETH_PRICE_DATA_SUCCESS = 'FETCHING_ETH_PRICE_DATA_SUCCESS';
export const FETCHING_ETH_PRICE_DATA_FAIL = 'FETCHING_ETH_PRICE_DATA_FAIL';
export const SET_WALLET_TOKENS_BALANCES = 'SET_WALLET_TOKENS_BALANCES';
export const CALCULATE_WALLET_BALANCE = 'CALCULATE_WALLET_BALANCE';
