export const UPDATE_TOKEN_BALANCE = 'update_token_balance';
export const TXN_FEE = 'txn_fee';
export const CONTACT_ADDRESS_TO_COINSEND = 'contact_address_to_coinsend';
export const ADD_NEW_TOKEN_ADDRESS = 'add_new_token_address';
export const ADD_NEW_TOKEN_NAME = 'add_new_token_name';
export const COMPLETE_NEW_TOKEN = 'complete_new_token';
export const CLEAR_STORE = 'clear_store';
export const RESET_WALLET_BALANCE = 'reset_wallet_balance';
export const ADD_TOKEN_FROM_LIST = 'add_token_from_list';
export const ADD_TOKEN_SETUP = "add_token_setup"; //good
export const CREATING_NEW_WALLET = 'creating_new_wallet'; //good
export const NEW_WALLET_NAME = 'new_wallet_name'; //good
export const SWITCH_LANGUAGE = 'switch_language';
export const CURRENT_WALLET = 'current_wallet';
export const SELECT_WALLET_CURRENCY = 'select_wallet_currency';
export const SELECT_WALLET_LANGUAGE = 'select_wallet_language';
export const QRSCANNER_DATA = 'qrscanner_data';
export const ADD_CONTACT = 'adding_contacts';
export const ADDING_CONTACT = 'adding_contact';
export const COMPLETE_CONTACT = 'complete_contact';
export const EDIT_CONTACT = 'edit_contact'
export const DELETE_CONTACT = 'delete_contact'
export const ACTIVE_CONTACT_TAB = 'active_contact_tab';
export const CONTACT_ADDRESS = 'contact_address';
export const QRSCANNER_PAGE_INVOKER = 'qrscanner_page_invoker';
export const QRSCANNER_COIN_INVOKER = 'qrscanner_coin_invoker';
export const SAVING_ADDCONTACT_INPUTS = 'saving_addContact_inputs';
export const UPDATE_SAVED_CONTACT_INPUTS = 'update_saved_contact_inputs';
export const ADD_TOKEN_INFO = 'add_token_info';