version: 2
jobs:
  build:
    branches:
          only: staging
    macos:
      xcode: "9.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: ios beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE --verbose
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  build:
    macos:
      xcode: "9.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: android beta
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE --verbose
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

#workflows:
#  version: 2
#  android-ios-beta:
#    jobs:
#      -beta-ios:
#        filters:
#          branches:
#            only: staging
#      -alpha-android:
#        filters:
#          branches:
#            only: staging
