fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
      match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
    end

  desc 'Build the iOS application.'
    private_lane :build do
      ensure_git_branch(branch: 'staging\/.+')
      certificates
      gym(scheme: 'weipay', project: './ios/weipay.xcodeproj')
    end

  desc 'Ship to Testflight.'
    lane :beta do
      build
      pilot(username: 'superadmin@chainsafe.io')
    end
end

platform :android do
  # Android Lanes
end
